### ISSUE TITLE
URL github page doesnt work

### ISSUE THREAD

**Issue by ariebrainware** [indrolie/api-project1#1]
This link doesnt work a.k.a 404: not found, i suggest you to make an index html in the parent directory, from there you need to link every level that you made.
![image](https://user-images.githubusercontent.com/26453961/43467891-f29cb28c-950c-11e8-930c-807e91431ab1.png)

@indrolie

**Comment by indrolie** [comment]
that's a very good idea.
thanks for your suggestion.
